// Generated by view binder compiler. Do not edit!
package com.chiller3.bcr.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.chiller3.bcr.R;
import com.google.android.material.chip.Chip;
import java.lang.NullPointerException;
import java.lang.Override;

public final class BottomSheetChipBinding implements ViewBinding {
  @NonNull
  private final Chip rootView;

  private BottomSheetChipBinding(@NonNull Chip rootView) {
    this.rootView = rootView;
  }

  @Override
  @NonNull
  public Chip getRoot() {
    return rootView;
  }

  @NonNull
  public static BottomSheetChipBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static BottomSheetChipBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.bottom_sheet_chip, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static BottomSheetChipBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    return new BottomSheetChipBinding((Chip) rootView);
  }
}
