// Generated by view binder compiler. Do not edit!
package com.chiller3.bcr.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.chiller3.bcr.R;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogTextInputBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final TextView bottomMessage;

  @NonNull
  public final TextView message;

  @NonNull
  public final TextInputEditText text;

  @NonNull
  public final TextInputLayout textLayout;

  private DialogTextInputBinding(@NonNull ScrollView rootView, @NonNull TextView bottomMessage,
      @NonNull TextView message, @NonNull TextInputEditText text,
      @NonNull TextInputLayout textLayout) {
    this.rootView = rootView;
    this.bottomMessage = bottomMessage;
    this.message = message;
    this.text = text;
    this.textLayout = textLayout;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogTextInputBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogTextInputBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_text_input, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogTextInputBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bottom_message;
      TextView bottomMessage = ViewBindings.findChildViewById(rootView, id);
      if (bottomMessage == null) {
        break missingId;
      }

      id = R.id.message;
      TextView message = ViewBindings.findChildViewById(rootView, id);
      if (message == null) {
        break missingId;
      }

      id = R.id.text;
      TextInputEditText text = ViewBindings.findChildViewById(rootView, id);
      if (text == null) {
        break missingId;
      }

      id = R.id.text_layout;
      TextInputLayout textLayout = ViewBindings.findChildViewById(rootView, id);
      if (textLayout == null) {
        break missingId;
      }

      return new DialogTextInputBinding((ScrollView) rootView, bottomMessage, message, text,
          textLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
