// Generated by view binder compiler. Do not edit!
package com.chiller3.bcr.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.chiller3.bcr.R;
import com.google.android.material.materialswitch.MaterialSwitch;
import java.lang.NullPointerException;
import java.lang.Override;

public final class MaterialSwitchPreferenceBinding implements ViewBinding {
  @NonNull
  private final MaterialSwitch rootView;

  @NonNull
  public final MaterialSwitch switchWidget;

  private MaterialSwitchPreferenceBinding(@NonNull MaterialSwitch rootView,
      @NonNull MaterialSwitch switchWidget) {
    this.rootView = rootView;
    this.switchWidget = switchWidget;
  }

  @Override
  @NonNull
  public MaterialSwitch getRoot() {
    return rootView;
  }

  @NonNull
  public static MaterialSwitchPreferenceBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MaterialSwitchPreferenceBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.material_switch_preference, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MaterialSwitchPreferenceBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    MaterialSwitch switchWidget = (MaterialSwitch) rootView;

    return new MaterialSwitchPreferenceBinding((MaterialSwitch) rootView, switchWidget);
  }
}
