// Generated by view binder compiler. Do not edit!
package com.chiller3.bcr.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.chiller3.bcr.R;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class OutputDirectoryBottomSheetBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final MaterialButton editRetention;

  @NonNull
  public final MaterialButton editTemplate;

  @NonNull
  public final TextView filenameTemplate;

  @NonNull
  public final TextView outputDir;

  @NonNull
  public final MaterialButton reset;

  @NonNull
  public final TextView retention;

  @NonNull
  public final MaterialButton selectNewDir;

  private OutputDirectoryBottomSheetBinding(@NonNull NestedScrollView rootView,
      @NonNull MaterialButton editRetention, @NonNull MaterialButton editTemplate,
      @NonNull TextView filenameTemplate, @NonNull TextView outputDir,
      @NonNull MaterialButton reset, @NonNull TextView retention,
      @NonNull MaterialButton selectNewDir) {
    this.rootView = rootView;
    this.editRetention = editRetention;
    this.editTemplate = editTemplate;
    this.filenameTemplate = filenameTemplate;
    this.outputDir = outputDir;
    this.reset = reset;
    this.retention = retention;
    this.selectNewDir = selectNewDir;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static OutputDirectoryBottomSheetBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static OutputDirectoryBottomSheetBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.output_directory_bottom_sheet, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static OutputDirectoryBottomSheetBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.edit_retention;
      MaterialButton editRetention = ViewBindings.findChildViewById(rootView, id);
      if (editRetention == null) {
        break missingId;
      }

      id = R.id.edit_template;
      MaterialButton editTemplate = ViewBindings.findChildViewById(rootView, id);
      if (editTemplate == null) {
        break missingId;
      }

      id = R.id.filename_template;
      TextView filenameTemplate = ViewBindings.findChildViewById(rootView, id);
      if (filenameTemplate == null) {
        break missingId;
      }

      id = R.id.output_dir;
      TextView outputDir = ViewBindings.findChildViewById(rootView, id);
      if (outputDir == null) {
        break missingId;
      }

      id = R.id.reset;
      MaterialButton reset = ViewBindings.findChildViewById(rootView, id);
      if (reset == null) {
        break missingId;
      }

      id = R.id.retention;
      TextView retention = ViewBindings.findChildViewById(rootView, id);
      if (retention == null) {
        break missingId;
      }

      id = R.id.select_new_dir;
      MaterialButton selectNewDir = ViewBindings.findChildViewById(rootView, id);
      if (selectNewDir == null) {
        break missingId;
      }

      return new OutputDirectoryBottomSheetBinding((NestedScrollView) rootView, editRetention,
          editTemplate, filenameTemplate, outputDir, reset, retention, selectNewDir);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
