// Generated by view binder compiler. Do not edit!
package com.chiller3.bcr.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.chiller3.bcr.R;
import com.chiller3.bcr.view.ChipGroupCentered;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class OutputFormatBottomSheetBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final ChipGroupCentered audioSourceGroup;

  @NonNull
  public final ChipGroupCentered nameGroup;

  @NonNull
  public final ChipGroupCentered paramGroup;

  @NonNull
  public final LinearLayout paramLayout;

  @NonNull
  public final TextView paramTitle;

  @NonNull
  public final MaterialButton reset;

  @NonNull
  public final ChipGroupCentered sampleRateGroup;

  @NonNull
  public final TextView stereoWarning;

  private OutputFormatBottomSheetBinding(@NonNull NestedScrollView rootView,
      @NonNull ChipGroupCentered audioSourceGroup, @NonNull ChipGroupCentered nameGroup,
      @NonNull ChipGroupCentered paramGroup, @NonNull LinearLayout paramLayout,
      @NonNull TextView paramTitle, @NonNull MaterialButton reset,
      @NonNull ChipGroupCentered sampleRateGroup, @NonNull TextView stereoWarning) {
    this.rootView = rootView;
    this.audioSourceGroup = audioSourceGroup;
    this.nameGroup = nameGroup;
    this.paramGroup = paramGroup;
    this.paramLayout = paramLayout;
    this.paramTitle = paramTitle;
    this.reset = reset;
    this.sampleRateGroup = sampleRateGroup;
    this.stereoWarning = stereoWarning;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static OutputFormatBottomSheetBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static OutputFormatBottomSheetBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.output_format_bottom_sheet, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static OutputFormatBottomSheetBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.audio_source_group;
      ChipGroupCentered audioSourceGroup = ViewBindings.findChildViewById(rootView, id);
      if (audioSourceGroup == null) {
        break missingId;
      }

      id = R.id.name_group;
      ChipGroupCentered nameGroup = ViewBindings.findChildViewById(rootView, id);
      if (nameGroup == null) {
        break missingId;
      }

      id = R.id.param_group;
      ChipGroupCentered paramGroup = ViewBindings.findChildViewById(rootView, id);
      if (paramGroup == null) {
        break missingId;
      }

      id = R.id.param_layout;
      LinearLayout paramLayout = ViewBindings.findChildViewById(rootView, id);
      if (paramLayout == null) {
        break missingId;
      }

      id = R.id.param_title;
      TextView paramTitle = ViewBindings.findChildViewById(rootView, id);
      if (paramTitle == null) {
        break missingId;
      }

      id = R.id.reset;
      MaterialButton reset = ViewBindings.findChildViewById(rootView, id);
      if (reset == null) {
        break missingId;
      }

      id = R.id.sample_rate_group;
      ChipGroupCentered sampleRateGroup = ViewBindings.findChildViewById(rootView, id);
      if (sampleRateGroup == null) {
        break missingId;
      }

      id = R.id.stereo_warning;
      TextView stereoWarning = ViewBindings.findChildViewById(rootView, id);
      if (stereoWarning == null) {
        break missingId;
      }

      return new OutputFormatBottomSheetBinding((NestedScrollView) rootView, audioSourceGroup,
          nameGroup, paramGroup, paramLayout, paramTitle, reset, sampleRateGroup, stereoWarning);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
