// Generated by view binder compiler. Do not edit!
package com.chiller3.bcr.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.chiller3.bcr.R;
import com.chiller3.bcr.view.ChipGroupCentered;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RecordRuleEditorBottomSheetBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final TextView actionDesc;

  @NonNull
  public final ChipGroupCentered actionGroup;

  @NonNull
  public final MaterialButton callNumberChange;

  @NonNull
  public final ChipGroupCentered callNumberGroup;

  @NonNull
  public final LinearLayout callNumberLayout;

  @NonNull
  public final TextView callNumberName;

  @NonNull
  public final ChipGroupCentered callTypeGroup;

  @NonNull
  public final LinearLayout callTypeLayout;

  @NonNull
  public final ChipGroupCentered simSlotGroup;

  @NonNull
  public final LinearLayout simSlotLayout;

  @NonNull
  public final TextView title;

  private RecordRuleEditorBottomSheetBinding(@NonNull NestedScrollView rootView,
      @NonNull TextView actionDesc, @NonNull ChipGroupCentered actionGroup,
      @NonNull MaterialButton callNumberChange, @NonNull ChipGroupCentered callNumberGroup,
      @NonNull LinearLayout callNumberLayout, @NonNull TextView callNumberName,
      @NonNull ChipGroupCentered callTypeGroup, @NonNull LinearLayout callTypeLayout,
      @NonNull ChipGroupCentered simSlotGroup, @NonNull LinearLayout simSlotLayout,
      @NonNull TextView title) {
    this.rootView = rootView;
    this.actionDesc = actionDesc;
    this.actionGroup = actionGroup;
    this.callNumberChange = callNumberChange;
    this.callNumberGroup = callNumberGroup;
    this.callNumberLayout = callNumberLayout;
    this.callNumberName = callNumberName;
    this.callTypeGroup = callTypeGroup;
    this.callTypeLayout = callTypeLayout;
    this.simSlotGroup = simSlotGroup;
    this.simSlotLayout = simSlotLayout;
    this.title = title;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static RecordRuleEditorBottomSheetBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RecordRuleEditorBottomSheetBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.record_rule_editor_bottom_sheet, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RecordRuleEditorBottomSheetBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.action_desc;
      TextView actionDesc = ViewBindings.findChildViewById(rootView, id);
      if (actionDesc == null) {
        break missingId;
      }

      id = R.id.action_group;
      ChipGroupCentered actionGroup = ViewBindings.findChildViewById(rootView, id);
      if (actionGroup == null) {
        break missingId;
      }

      id = R.id.call_number_change;
      MaterialButton callNumberChange = ViewBindings.findChildViewById(rootView, id);
      if (callNumberChange == null) {
        break missingId;
      }

      id = R.id.call_number_group;
      ChipGroupCentered callNumberGroup = ViewBindings.findChildViewById(rootView, id);
      if (callNumberGroup == null) {
        break missingId;
      }

      id = R.id.call_number_layout;
      LinearLayout callNumberLayout = ViewBindings.findChildViewById(rootView, id);
      if (callNumberLayout == null) {
        break missingId;
      }

      id = R.id.call_number_name;
      TextView callNumberName = ViewBindings.findChildViewById(rootView, id);
      if (callNumberName == null) {
        break missingId;
      }

      id = R.id.call_type_group;
      ChipGroupCentered callTypeGroup = ViewBindings.findChildViewById(rootView, id);
      if (callTypeGroup == null) {
        break missingId;
      }

      id = R.id.call_type_layout;
      LinearLayout callTypeLayout = ViewBindings.findChildViewById(rootView, id);
      if (callTypeLayout == null) {
        break missingId;
      }

      id = R.id.sim_slot_group;
      ChipGroupCentered simSlotGroup = ViewBindings.findChildViewById(rootView, id);
      if (simSlotGroup == null) {
        break missingId;
      }

      id = R.id.sim_slot_layout;
      LinearLayout simSlotLayout = ViewBindings.findChildViewById(rootView, id);
      if (simSlotLayout == null) {
        break missingId;
      }

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      return new RecordRuleEditorBottomSheetBinding((NestedScrollView) rootView, actionDesc,
          actionGroup, callNumberChange, callNumberGroup, callNumberLayout, callNumberName,
          callTypeGroup, callTypeLayout, simSlotGroup, simSlotLayout, title);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
